### ISSUE TITLE
Faturacao em Portugal

### ISSUE THREAD

**Issue by Fonoa** [joaomfrebelo/Saft-PT_4_PHP#1]
Hi Joao, 

first of all apologies for opening an issue but I wasn't able to find an alternative way to contact you.

I saw your work related to invoicing in Portugal and wanted to reach out with a few questions. We are a European electronic invoicing company that, amongst other countries, works in Portugal as well. Our software has already obtained certification by the Autoridade Tributaria for Web service, but we have a few technical questions that we are seeking expert advice on. Since you seem to be more than qualified, I was wondering whether you would be open to consult us on the topic? If that sounds interesting please let me know your email or reach out to my email (can be found in my bio). 

Best regards,
Filip

**Comment by joaomfrebelo** [comment]
Hi Filip,
the company where i work we among software developing we also give support to foreigner companies like yours, technical support or developing modules to integrate with Portuguese AT. 
The company where i work is PChouse  - https://www.pchouse.pt/
If you wont send a email to joao.rebelo@pchouse.pt with the type of support needed and i will send you a quote.

Best Regards

João Rebelo

**Comment by joaomfrebelo** [comment]
Hi Filip i don't know if you are having troubles with AT webservice
regarding with the MovementOfGoods webservice, but unfortunately a bug in
the AT webservice was discovered, the Webservice test environment of
MovementOfGoods is not working with the public key of the test environment,
but wrongly is working with the public key of the production envoirment.
If are you getting problems try the test environment with the public key of
the production environment, the SalesInvoices webservice is working nice.
Other thing the public keys had changed last month, if you did not download
yet, you have to go to the AT (e-fatura) portal download the latest keys.
The problem happens with the old and new keys. I had reported the bug today
to AT.

Filip Sturman <notifications@github.com> escreveu no dia terça, 31/03/2020
à(s) 11:04:

**Comment by Fonoa** [comment]
Many thanks Joao for letting me know. Really appreciate it!
