### ISSUE TITLE
Modulo para Dollibar

### ISSUE THREAD

**Issue by ct2glx** [joaomfrebelo/Saft-PT_4_PHP#3]
Lamento usar esta forma de comunicar mas nao encontrei outra :)

Faria sentido pensar num modulo para o dollibar? (com base na sua biblioteca?)

**Comment by joaomfrebelo** [comment]
Fazer sentido ou não depende. Em Portugal um software de faturação para puder ser usado tem que estar certificado pelas finanças, o simples facto de o software gerar o ficheiro saft não é suficiente para ser certificado, só faz sentido fazer se também se implementar todas as outras regras que são exigidas para a certificação, assinatura de documentos, comunicação das séries de documentos à AT, geração do QRcode com ATCUD nas faturas e muitas outras regras.
Não me parece que apenas com a criação de módulos seja possível implementar todas as regras, presumo que só com um fork e implementação das alterações.
Contudo deixo aqui link de outros projectos meus que podem auxiliar na implementação das exigências de certificação:

Comunicação web service AT:
https://github.com/joaomfrebelo/atws

Geração de QRcode ATCUD:
https://github.com/joaomfrebelo/at_qrcode

App Android para verificação de erros no QRcode (pode ser usada com qualquer fatura de qualquer software):
https://play.google.com/store/apps/details?id=pt.pchouse.atqrcodereader

Impressão de documentos em PHP com JasperReports:
https://github.com/joaomfrebelo/reports_4_php
https://github.com/pchouse/reports_api
