### ISSUE TITLE
Modo de desenvolvedor?

### ISSUE THREAD

**Issue by daniel89fg** [joaomfrebelo/Saft-PT_4_PHP#5]
Olá.

Estou implementando esta biblioteca para a assinatura eletrônica de minhas faturas com FacturaScripts da Espanha.

Como posso ativar o modo de desenvolvedor? Preciso de poder enviar faturas para o modo sandbox do tesouro português. Você pode me explicar como fazer isso para trabalhar com local?

Obrigado.

**Comment by joaomfrebelo** [comment]
Se precisa de suporte deve optar pela vesão EE e comprar horas suporte.

https://github.com/pchouse/Saft-PT_4_PHP

Professional support:

https://www.pchouse.pt/

[joao.rebelo@pchouse.pt](mailto:joao.rebelo@pchouse.pt)

**Comment by daniel89fg** [comment]
Não preciso de suporte, obrigado.

Eu só preciso saber como enviar uma fatura assinada no modo de prova. Na documentação de exemplo, explica como criar e validar a assinatura, mas não explica como enviar a assinatura em modo de teste, apenas em modo de produção.
